### ISSUE TITLE
visualization: create dashboard

### ISSUE THREAD

**Issue by eamonnmag** [thor-project/dashboard#3]

**Comment by eamonnmag** [comment]
![thor-db](https://cloud.githubusercontent.com/assets/282396/9688519/facb6f88-532f-11e5-9fea-a9ea9a5d6b73.gif)

**Comment by suenjedt** [comment]
Like it!

**Comment by daslerr** [comment]
Just to clarify a few points about the underlying data . . . 

The overview at the top currently shows how many DataCite DOIs are minted, and how many of those have associated ORCIDs, right? Our current trouble is that each identifier doesn’t necessarily know about the other, which is part of what THOR will be trying to fix. So if we look at the information from ORCID and ask how many ORCIDs have DataCite DOIs included in the works information, the answer at the moment will be very different than the information DataCite knows about. Is there a way to incorporate these two different perspectives into the overview in a way that isn’t super confusing? 

The “ORCIDs Created” information is currently showing associated data centres, but not all ORCIDs will be created at a DataCite data centre. Is this category intended for information coming from DataCite about the ORCIDs that are associated with data sets from particular data centres? In that case, it should probably be “ORCIDs Included by Data Centres” or something. It would be great if we could gather the ORCID affiliation information from ORCID itself and cross reference that with DataCite data centres, where there are matches, but that metadata doesn’t line up real well between the two entities (or isn't always provided), so that sounds too difficult for a pre-focus group version.

**Comment by eamonnmag** [comment]
Ok, got it. I'm going to work on this more next week. Been busy this week at Durham and have had little time to do much else.

**Comment by eamonnmag** [comment]
New version. Just need to add the overview part of the dashboard in. I think this much better addresses the use cases in your document @daslerr and @suenjedt .

![thor-db](https://cloud.githubusercontent.com/assets/282396/9885825/7d3d017e-5be7-11e5-9436-82103bb7b935.gif)
